### ISSUE TITLE
ID change requires separate click per character

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/fresco#52]
Editing an id requires you to click inside the id quotes for each letter.

**Comment by justenPalmer** [comment]
@PetersonGIS, while it is possible to change a layer ID through the JSON editor, it's difficult to support because of the way the data syncs with every change and has to re-navigate the user back to the page (the layer ID is used in the page path). However, there is another supported way of changing the ID which works seamlessly. Just click on the layer ID in the top bar and it will change to input field where you can change the ID. Because the change is only propagated when you press enter, it doesn't mess with the user experience.

<img width="303" alt="screen shot 2018-06-11 at 3 38 22 am" src="https://user-images.githubusercontent.com/1915862/41227294-1e40d83e-6d29-11e8-90e7-bec83b74be67.png">

I need to document this functionality and figure out a way of relating the ID should not be changed in the JSON directly.

**Comment by PetersonGIS** [comment]
Ok, didn't realize you could change it up there. Good to know. 

Definitely something to make other users aware of somehow. Thanks.

**Comment by justenPalmer** [comment]
ID changes should no longer cause any issues on dev.
